#!/bin/sh

#PBS -l mem=14gb,nodes=8:ppn=1,walltime=36:00:00 
#PBS -m abe 
#PBS -M liux1299@umn.edu 
#PBS -q lab

#	Required for Java
module load java

#	The root of where we will work
PROJECT_DIR=${HOME}/Projects/IPK_ExomeCapture_Disk_1-3
#	And the sample
SAMPLE="XXXXX"
#	The date of the alignment
ALIGN_DATE="2014-07-10"
#	The programs we are using
SAMTOOLS=${HOME}/Shared/Software/samtools-0.1.19/samtools
PICARD_SORT=${HOME}/Shared/Software/picard-tools-1.110/SortSam.jar
ADDRG=${HOME}/Shared/Software/picard-tools-1.110/AddOrReplaceReadGroups.jar
MARKDUPS=${HOME}/Shared/Software/picard-tools-1.110/MarkDuplicates.jar

#	The alignment we are processing
ALIGNMENT=${SAMPLE}_${ALIGN_DATE}.sam
#	cd into the directory
cd ${PROJECT_DIR}/${SAMPLE}

#	Use Samtools to trim out the reads we don't care about
#	-f 3 gives us reads mapped in proper pair
#	-F 256 excludes reads not in their primary alignments
$SAMTOOLS view -f 3 -F 256 -bS ${ALIGNMENT} > ${ALIGNMENT/.sam/_trimmed.bam}

#	Picard tools to sort and index
java -Xmx13g -XX:MaxPermSize=10g -jar\
	${PICARD_SORT} \
	INPUT=${ALIGNMENT/.sam/_trimmed.bam} \
	OUTPUT=${ALIGNMENT/.sam/_Sorted.bam}\
	SORT_ORDER=coordinate \
	CREATE_INDEX=true\
	TMP_DIR=${HOME}/Scratch/Picard_Tmp

#	Then remove duplicates
java -Xmx13g -XX:MaxPermSize=10g -jar\
	${MARKDUPS} \
	INPUT=${ALIGNMENT/.sam/_Sorted.bam}\
	OUTPUT=${ALIGNMENT/.sam/_NoDups.bam} \
	METRICS_FILE=${SAMPLE}_${ALIGN_DATE}_Metrics.txt\
	REMOVE_DUPLICATES=true\
	CREATE_INDEX=true\
	TMP_DIR=${HOME}/Scratch/Picard_Tmp\
	MAX_RECORDS_IN_RAM=50000

#	Then add read groups
java -Xmx13g -XX:MaxPermSize=10g -jar\
	${ADDRG} \
	INPUT=${ALIGNMENT/.sam/_NoDups.bam} \
	OUTPUT=${ALIGNMENT/.sam/_Finished.bam} \
	RGID=${SAMPLE}\
	RGPL=Illumina\
	RGPU=${SAMPLE}\
	RGSM=${SAMPLE}\
	RGLB=${SAMPLE}\
	TMP_DIR=${HOME}/Scratch/Picard_Tmp\
	CREATE_INDEX=True

#	Get rid of everything except the finished BAM file
#find . -type f -not -name '*Finished*' | xargs rm
